apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: phaneesh707/consumer:2.5
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo helllo; sleep 10;done"]
          imagePullPolicy: Always
